language: python

git:
  depth: 99999


matrix:
  include:
   - python: 3.6

before_install:
 - cp config.py.example config.py

install:
 - pip install -r requirements.txt
 - pip install codecov
 - pip install pytest-cov
 - pip install pep8
 - pip install flake8


before_script:
 - "export PYTHONPATH=."


script:
 - python -m pytest tests