version: '3'
services:

  nginx:
    build: ./nginx
    restart: always
    ports: 
    - 5010:80
    depends_on:
    - manager
    networks:
    - share
  
  manager:
    build: .
    restart: always
    ports:
     - "5011:5011"
     - "10023:22"
    volumes:
     - .:/app
    env_file:
      - ./keys/simulator.env
    environment:
      - FLASK_CONFIGURATION=development
      - ENV_FLASK_APP=app.py
    networks:
    - share
    command: gunicorn -w 1 -b :5011 app:app

networks:
  share:
    driver: bridge