version: '3'
services:
  manager:
    build: .
    ports:
     - "5010:5010"
     - "10023:22"
    volumes:
     - .:/app
    env_file:
      - ./keys/simulator.env
    environment:
      - FLASK_CONFIGURATION=development
      - ENV_FLASK_APP=app.py
    command: gunicorn -w 1 -b :5010 app:app --reload
